### ISSUE TITLE
[Bug] Card 클래스명 material.dart의 Card와 중복됨

### ISSUE THREAD

**Issue by ja7811** [CSOneCup/CsOneCup-client#29]
## 구현 & 수정할 기능
- data/models 패키지의 `Card` 클래스 명 수정

## 작업 예상시간
- 약 1시간

## Note
![image](https://github.com/user-attachments/assets/c97187a3-bc7b-4592-8e9c-7dc825236f75)
- Card 클래스가 material 패키지와 data/models 패키지와 중복되어 에러 발생
- Card 모델을 CardModel 등으로 개명해야 함 -> 이름 추천 받음

**Comment by SHKim55** [comment]
QuizCard 어떰

**Comment by ja7811** [comment]
ㅇㅋ 회의 때 말함
